### ISSUE TITLE
docker container - npm scan error

### ISSUE THREAD

**Issue by tamirach** [DataDog/guarddog#191] opened 2023-03-06 13:43 UTC
sometimes I've got the following error

![image](https://user-images.githubusercontent.com/121603889/223126843-31ab2007-6578-48cf-a4c2-8b0acfdea313.png)

**Comment by christophetd** [comment] 2023-03-08 09:25
Hello!

I couldn't reproduce the issue after several tries of testing, this looks like a temporary network issue on your side or on npm's side - not coming from GuardDog.

I'll close the issue, but feel free to reopen if you have reasons to believe this is coming from GuardDog!

**Closed by christophetd** 2023-03-08 09:25 UTC
